# fly.toml app configuration file generated for mnb-remix on 2023-07-02T13:35:47+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mnb-remix"
primary_region = "cdg"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
